name = "shx-worker"
compatibility_date = "2023-01-01"

[vars]
MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "SHX_SETTINGS"
id = "be1c00f6dc064c8aa5756fb58400d420"

[[r2_buckets]]
binding = "SHX_BUCKET"
bucket_name = "shx"