-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."uploads" add column "deleteToken" Text
--  not null default generate_short_url();
