name: 💡 Apply Done Label
on:
  pull_request:
    types: [opened, merged, closed]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: logerfo/close-label@0.0.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}