name: Build Checks for CLI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: cd apps/cli/ && yarn && yarn build && yarn r
      - run: shx help
      - run: du -sh
