name: Build Checks

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set output
          id: vars
          run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
        - name: Build and Publish latest Docker image
          uses: TCPShield/gp-docker-action@1.1.3
          with:
              github-token: ${{ secrets.GITHUB_TOKEN }}
              image-name: shx-server-api
              dockerfile: Dockerfile
              image-tag: latest
        - name: Build and Publish to GitHub Releases
          uses: actions/create-release@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ steps.vars.outputs.tag }}
              release_name: ${{ steps.vars.outputs.tag }}
              draft: false
              prerelease: false