name: 💡 PR Branch Labeler
on: pull_request
jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Label PR
      if: github.event.action == 'opened'
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}