name: Test

on:
  push:
  pull_request:

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Write ENV_FILE to packages/api/.env
      run: |
        wget ${{ secrets.ENV_FILE }} -O packages/api/.env
        
    - name: Start containers
      run: cd packages/api && docker compose -f "docker-compose.yaml" up -d --build

    - name: Wait for containers
      run: sleep 30

    - name: Run tests
      run: curl --location --request POST http://localhost:4006/apikey?masterkey=${{ secrets.DEMO_MASTER_KEY }}